blank_issues_enabled: true

contact_links:
  - name: Blazium Web Editor
    url: https://github.com/blazium-engine/blazium
    about: Please report issues with the web editor on the Blazium repository, not here.

  - name: Blazium proposals
    url: https://chat.blazium.app
    about: Please submit feature proposals on the Blazium Discord server, not here.

  - name: Blazium documentation repository
    url: https://github.com/blazium-engine/blazium-docs
    about: Please report issues with documentation on the Blazium documentation repository, not here.
